from tensorflow.keras.preprocessing.image import ImageDataGenerator
from matplotlib.pyplot import imread, imshow, subplots, show
import numpy as np


def data_Augment(data_generator, images, limit=10):
    """
    Plots 4 images generated by an object of the ImageDataGenerator class.
    """

    data_generator.fit(images)
    image_iterator = data_generator.flow(images)
    genarated_data = np.array([image_iterator.next()[0]])
    limit -= 1
    for image in image_iterator:
        # genarated_data = np.append((genarated_data, [image[0]]), axis=0)
        genarated_data = np.append(genarated_data, [image[0]], axis=0)
        limit -= 1
        if limit <= 0:
            break

    return genarated_data

# image = imread("res/img/skeleton.png")

# # Creating a dataset which contains just one image.
# images = image.reshape((1, image.shape[0], image.shape[1], image.shape[2]))

# imshow(images[0])
# show()

# data_generator = ImageDataGenerator(rotation_range=90,
#                                     zoom_range=0.15,
#                                     width_shift_range=0.2,
#                                     height_shift_range=0.2,
#                                     shear_range=0.15,
#                                     horizontal_flip=True,
#                                     fill_mode="nearest")
# # plot(data_generator)
